In [1]:
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os

In [2]:
%matplotlib inline
plt.rcParams['figure.figsize'] = (20, 10)

In [3]:
saved_style_state = matplotlib.rcParams.copy() #give us a style state to go back to

In [4]:
e_data = pd.read_excel("emissions.xlsx")

In [6]:
e_data.head()

,report_id,report_year,facility_id,jurisdiction_code,jurisdiction_facility_id,facility_name,registered_business_name,primary_anzsic_class_code,primary_anzsic_class_name,substance_id,...,water_emission_kg,water_eet,land_emission_kg,land_eet,suburb,state,postcode,latitude,longitude,pivot_facility_name
0,500972,2017/2018,516654,SA,SA0152,YALDARA ESTATE,1847 WINERY (SA) PTY LTD,1214,Wine and Other Alcoholic Beverage Manufacturing,37,...,NaN,NaN,NaN,NaN,Lyndoch,SA,5351.0,-34.576046,138.875311,"YALDARA ESTATE, Lyndoch SA (SA0152)"
1,500972,2017/2018,516654,SA,SA0152,YALDARA ESTATE,1847 WINERY (SA) PTY LTD,1214,Wine and Other Alcoholic Beverage Manufacturing,85,...,NaN,NaN,NaN,NaN,Lyndoch,SA,5351.0,-34.576046,138.875311,"YALDARA ESTATE, Lyndoch SA (SA0152)"
2,504680,2017/2018,545702,WA,WA0685,3 Oceans Wine Company,3 OCEANS WINE COMPANY PTY LTD,1214,Wine and Other Alcoholic Beverage Manufacturing,37,...,NaN,NaN,NaN,NaN,Metricup,WA,6280.0,-33.814167,115.119444,"3 Oceans Wine Company, Metricup WA (WA0685)"
3,504680,2017/2018,545702,WA,WA0685,3 Oceans Wine Company,3 OCEANS WINE COMPANY PTY LTD,1214,Wine and Other Alcoholic Beverage Manufacturing,85,...,NaN,NaN,NaN,NaN,Metricup,WA,6280.0,-33.814167,115.119444,"3 Oceans Wine Company, Metricup WA (WA0685)"
4,501896,2017/2018,511502,QLD,Q063AAG001,Goonoo Feedlot,A A COMPANY PTY LTD,143,Beef Cattle Feedlots (Specialised),8,...,NaN,NaN,NaN,NaN,Comet,QLD,4702.0,-23.757823,148.528012,"Goonoo Feedlot, Comet QLD (Q063AAG001)"

In [7]:
e_data.columns

Index(['report_id', 'report_year', 'facility_id', 'jurisdiction_code',
       'jurisdiction_facility_id', 'facility_name', 'registered_business_name',
       'primary_anzsic_class_code', 'primary_anzsic_class_name',
       'substance_id', 'substance_sort_order', 'substance_name',
       'air_point_emission_kg', 'air_point_eet', 'air_fugitive_emission_kg',
       'air_fugitive_eet', 'air_total_emission_kg', 'water_emission_kg',
       'water_eet', 'land_emission_kg', 'land_eet', 'suburb', 'state',
       'postcode', 'latitude', 'longitude', 'pivot_facility_name'],
      dtype='object')

In [8]:
e_data.loc[0]

report_id                                                             500972
report_year                                                        2017/2018
facility_id                                                           516654
jurisdiction_code                                                         SA
jurisdiction_facility_id                                              SA0152
facility_name                                                 YALDARA ESTATE
registered_business_name                            1847 WINERY (SA) PTY LTD
primary_anzsic_class_code                                               1214
primary_anzsic_class_name    Wine and Other Alcoholic Beverage Manufacturing
substance_id                                                              37
substance_sort_order                                                      39
substance_name                                                       Ethanol
air_point_emission_kg                                                    NaN
air_point_eet                                                            NaN
air_fugitive_emission_kg                                              3536.9
air_fugitive_eet                                                       ___4_
air_total_emission_kg                                                 3536.9
water_emission_kg                                                        NaN
water_eet                                                                NaN
land_emission_kg                                                         NaN
land_eet                                                                 NaN
suburb                                                               Lyndoch
state                                                                     SA
postcode                                                                5351
latitude                                                             -34.576
longitude                                                            138.875
pivot_facility_name                      YALDARA ESTATE, Lyndoch SA (SA0152)
Name: 0, dtype: object

In [29]:
state = e_data["state"]
print(state)
state_series = pd.Series(state)
print(state_series)
nsw_emi = ["nsw" in state for state in state_series]
print(nsw_emi)

state_series[nsw_emi]

0          SA
1          SA
2          WA
3          WA
4         QLD
5         QLD
6         QLD
7         QLD
8         QLD
9         QLD
10        QLD
11        QLD
12        QLD
13        VIC
14        VIC
15        VIC
16        VIC
17        VIC
18        VIC
19        VIC
20        VIC
21        VIC
22        VIC
23        VIC
24        VIC
25        VIC
26        VIC
27        VIC
28        VIC
29        VIC
         ...
699742    QLD
699743    QLD
699744    QLD
699745    QLD
699746    QLD
699747    QLD
699748    QLD
699749    VIC
699750    VIC
699751    VIC
699752    VIC
699753    VIC
699754    QLD
699755    QLD
699756    QLD
699757    QLD
699758    QLD
699759    QLD
699760    QLD
699761     WA
699762     WA
699763     WA
699764     WA
699765     WA
699766     WA
699767     WA
699768     WA
699769     WA
699770     WA
699771     WA
Name: state, Length: 699772, dtype: object
0          SA
1          SA
2          WA
3          WA
4         QLD
5         QLD
6         QLD
7         QLD
8         QLD
9         QLD
10        QLD
11        QLD
12        QLD
13        VIC
14        VIC
15        VIC
16        VIC
17        VIC
18        VIC
19        VIC
20        VIC
21        VIC
22        VIC
23        VIC
24        VIC
25        VIC
26        VIC
27        VIC
28        VIC
29        VIC
         ...
699742    QLD
699743    QLD
699744    QLD
699745    QLD
699746    QLD
699747    QLD
699748    QLD
699749    VIC
699750    VIC
699751    VIC
699752    VIC
699753    VIC
699754    QLD
699755    QLD
699756    QLD
699757    QLD
699758    QLD
699759    QLD
699760    QLD
699761     WA
699762     WA
699763     WA
699764     WA
699765     WA
699766     WA
699767     WA
699768     WA
699769     WA
699770     WA
699771     WA
Name: state, Length: 699772, dtype: object

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

Series([], Name: state, dtype: object)